//! Compiles the design tokens into Rust (ARCHITECTURE.md, Design tokens in the build).
//!
//! Reads `design-system/tokens/design.resolver.json`, loads the files its
//! sets and modifiers name, resolves every alias for each palette and theme,
//! and writes `tokens.rs` into `OUT_DIR`:
//!
//! - the `Role` enum of every `color.*` role, and one `Colors` value per
//!   palette and theme holding each role's colour;
//! - one constant per foundation token (dimensions in pixels, dash arrays,
//!   type styles, durations in milliseconds, numbers, the font stack).
//!
//! Only the DTCG features the tokens use are supported; anything else fails
//! the build with the token's id, so a new kind of token is noticed at once.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

type Tokens = BTreeMap<String, (String, Value)>;

// One linear script: reading the resolver, resolving per theme, writing the file.
#[allow(clippy::too_many_lines)]
fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dir = manifest.join("../../design-system/tokens");
    let resolver_path = dir.join("design.resolver.json");
    println!("cargo:rerun-if-changed={}", resolver_path.display());
    let resolver = read_json(&resolver_path);

    let refs = |v: &Value| -> Vec<PathBuf> {
        v.as_array()
            .expect("a list of sources")
            .iter()
            .map(|s| dir.join(s["$ref"].as_str().expect("a $ref")))
            .collect()
    };
    let mut foundation = Tokens::new();
    for file in refs(&resolver["sets"]["foundation"]["sources"]) {
        load(&file, &mut foundation);
    }
    let contexts = |modifier: &str| -> BTreeMap<String, Vec<PathBuf>> {
        resolver["modifiers"][modifier]["contexts"]
            .as_object()
            .unwrap_or_else(|| panic!("the resolver has no `{modifier}` modifier"))
            .iter()
            .map(|(name, sources)| (name.clone(), refs(sources)))
            .collect()
    };
    let palettes = contexts("palette");
    let themes = contexts("theme");

    let mut out =
        String::from("// Generated by build.rs from design-system/tokens/. Do not edit.\n\n");
    let mut colors_struct: Option<Vec<String>> = None;
    let mut entries = Vec::new();
    for (palette, palette_files) in &palettes {
        for (theme, theme_files) in &themes {
            let mut all = foundation.clone();
            for file in palette_files.iter().chain(theme_files) {
                load(file, &mut all);
            }
            let roles: BTreeMap<String, String> = all
                .iter()
                .filter(|(id, (ty, _))| id.starts_with("color.") && ty == "color")
                .map(|(id, _)| (id["color.".len()..].to_owned(), hex(&resolve(&all, id))))
                .collect();
            let names: Vec<String> = roles.keys().cloned().collect();
            match &colors_struct {
                None => colors_struct = Some(names),
                Some(first) => assert_eq!(
                    first, &names,
                    "palette `{palette}` theme `{theme}` defines different colour roles"
                ),
            }
            let fields = roles.iter().fold(String::new(), |mut acc, (k, v)| {
                let _ = write!(acc, "{}: {}, ", field(k), rgb(v));
                acc
            });
            entries.push(format!(
                "    Theme {{ palette: \"{palette}\", theme: \"{theme}\", colors: Colors {{ {fields}}} }},\n"
            ));
        }
    }

    let names = colors_struct.expect("at least one palette and theme");
    out.push_str("/// Every colour role, by its token name under `color.`.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\npub enum Role {\n");
    for n in &names {
        let _ = writeln!(out, "    /// `color.{n}`\n    {},", variant(n));
    }
    out.push_str("}\n\nimpl Role {\n    /// Every role, in name order.\n");
    let _ = writeln!(
        out,
        "    pub const ALL: [Role; {}] = [{}];\n",
        names.len(),
        names
            .iter()
            .map(|n| format!("Role::{}", variant(n)))
            .collect::<Vec<_>>()
            .join(", ")
    );
    out.push_str("    /// The token name, such as `card-edge`.\n    #[must_use]\n    pub fn name(self) -> &'static str {\n        match self {\n");
    for n in &names {
        let _ = writeln!(out, "            Role::{} => \"{n}\",", variant(n));
    }
    out.push_str("        }\n    }\n\n    /// The role a token name names.\n    #[must_use]\n    pub fn from_name(name: &str) -> Option<Role> {\n        Role::ALL.into_iter().find(|r| r.name() == name)\n    }\n}\n\n");
    out.push_str("/// Every colour role's colour, for one palette and theme.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct Colors {\n");
    for n in &names {
        let _ = writeln!(out, "    /// `color.{n}`\n    pub {}: Rgb,", field(n));
    }
    out.push_str("}\n\nimpl Colors {\n    /// A role's colour.\n    #[must_use]\n    pub fn get(&self, role: Role) -> Rgb {\n        match role {\n");
    for n in &names {
        let _ = writeln!(
            out,
            "            Role::{} => self.{},",
            variant(n),
            field(n)
        );
    }
    out.push_str("        }\n    }\n\n    /// Sets a role's colour.\n    pub fn set(&mut self, role: Role, colour: Rgb) {\n        match role {\n");
    for n in &names {
        let _ = writeln!(
            out,
            "            Role::{} => self.{} = colour,",
            variant(n),
            field(n)
        );
    }
    out.push_str("        }\n    }\n\n    /// Every role with its token name (`card-edge`) and colour, in name order.\n    #[must_use]\n    pub fn roles(&self) -> [(&'static str, Rgb); ");
    let _ = write!(out, "{}] {{\n        [", names.len());
    for n in &names {
        let _ = write!(out, "(\"{n}\", self.{}), ", field(n));
    }
    out.push_str("]\n    }\n");
    out.push_str("}\n\n/// One palette in one theme.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct Theme {\n    pub palette: &'static str,\n    pub theme: &'static str,\n    pub colors: Colors,\n}\n\n");
    let _ = writeln!(
        out,
        "/// Every palette in every theme.\npub const THEMES: &[Theme] = &[\n{}];\n",
        entries.concat()
    );
    let _ = writeln!(
        out,
        "/// The palettes, in the resolver's order.\npub const PALETTES: &[&str] = &[{}];\n",
        palettes
            .keys()
            .map(|p| format!("\"{p}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let _ = writeln!(
        out,
        "/// A type style (`typography.*`).\n#[derive(Debug, Clone, Copy, PartialEq)]\npub struct TextStyle {{\n    pub size: f64,\n    pub weight: u16,\n    pub line_height: f64,\n    pub letter_spacing: f64,\n}}\n"
    );

    // Foundation constants: the same in every palette and theme.
    for (id, (ty, _)) in &foundation {
        let value = resolve(&foundation, id);
        let name = constant(id);
        let doc = format!("/// `{id}`\n");
        let line = match ty.as_str() {
            "dimension" => format!("pub const {name}: f64 = {};\n", px(&value, id)),
            "number" => format!("pub const {name}: f64 = {};\n", number(&value, id)),
            "duration" => format!("pub const {name}_MS: f64 = {};\n", ms(&value, id)),
            "cubicBezier" => {
                let v: Vec<String> = value
                    .as_array()
                    .expect("four numbers")
                    .iter()
                    .map(|n| number(n, id))
                    .collect();
                format!("pub const {name}: [f64; 4] = [{}];\n", v.join(", "))
            }
            "strokeStyle" => {
                let dashes: Vec<String> = value["dashArray"]
                    .as_array()
                    .expect("a dash array")
                    .iter()
                    .map(|d| px(d, id))
                    .collect();
                format!("pub const {name}: &[f64] = &[{}];\n", dashes.join(", "))
            }
            "fontFamily" => {
                let stack: Vec<String> = match &value {
                    Value::Array(a) => a
                        .iter()
                        .map(|f| f.as_str().expect("a family name").to_owned())
                        .collect(),
                    Value::String(s) => vec![s.clone()],
                    _ => panic!("{id}: a font family is a string or a list"),
                };
                let css: Vec<String> = stack
                    .iter()
                    .map(|f| {
                        if f.contains(' ') {
                            format!("\\\"{f}\\\"")
                        } else {
                            f.clone()
                        }
                    })
                    .collect();
                format!("pub const {name}: &str = \"{}\";\n", css.join(", "))
            }
            "typography" => format!(
                "pub const {name}: TextStyle = TextStyle {{ size: {}, weight: {}, line_height: {}, letter_spacing: {} }};\n",
                px(&value["fontSize"], id),
                value["fontWeight"]
                    .as_u64()
                    .unwrap_or_else(|| panic!("{id}: fontWeight")),
                number(&value["lineHeight"], id),
                px(&value["letterSpacing"], id),
            ),
            other => panic!("{id}: token type `{other}` is not supported by build.rs"),
        };
        out.push_str(&doc);
        out.push_str(&line);
    }

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tokens.rs");
    std::fs::write(dest, out).expect("write tokens.rs");
}

fn read_json(path: &Path) -> Value {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// Adds every token in `file` to `into`, keyed by its dotted id, with its type
/// (inherited from the nearest group that sets `$type`). Later files win.
fn load(file: &Path, into: &mut Tokens) {
    println!("cargo:rerun-if-changed={}", file.display());
    walk(&read_json(file), &mut Vec::new(), None, into);
}

/// One level of [`load`]: a token when the node has `$value`, else a group to descend.
fn walk(node: &Value, path: &mut Vec<String>, ty: Option<&str>, into: &mut Tokens) {
    let Some(obj) = node.as_object() else { return };
    let ty = obj.get("$type").and_then(Value::as_str).or(ty);
    if let Some(value) = obj.get("$value") {
        let id = path.join(".");
        let ty = ty.unwrap_or_else(|| panic!("{id}: no $type")).to_owned();
        into.insert(id, (ty, value.clone()));
        return;
    }
    for (key, child) in obj {
        if key.starts_with('$') {
            continue;
        }
        path.push(key.clone());
        walk(child, path, ty, into);
        path.pop();
    }
}

/// A token's value with every `{alias}` replaced by what it points to, recursively.
fn resolve(tokens: &Tokens, id: &str) -> Value {
    fn go(tokens: &Tokens, v: &Value, depth: usize) -> Value {
        assert!(depth < 16, "alias chain too deep");
        match v {
            Value::String(s) if s.starts_with('{') && s.ends_with('}') => {
                let target = &s[1..s.len() - 1];
                let (_, value) = tokens
                    .get(target)
                    .unwrap_or_else(|| panic!("alias to a missing token: {s}"));
                go(tokens, value, depth + 1)
            }
            Value::Object(o) => Value::Object(
                o.iter()
                    .map(|(k, x)| (k.clone(), go(tokens, x, depth)))
                    .collect(),
            ),
            Value::Array(a) => Value::Array(a.iter().map(|x| go(tokens, x, depth)).collect()),
            other => other.clone(),
        }
    }
    go(tokens, &tokens[id].1, 0)
}

fn hex(v: &Value) -> String {
    v["hex"]
        .as_str()
        .expect("a colour with a hex value")
        .to_lowercase()
}

fn px(v: &Value, id: &str) -> String {
    assert_eq!(
        v["unit"].as_str(),
        Some("px"),
        "{id}: only px dimensions are supported"
    );
    number(&v["value"], id)
}

fn ms(v: &Value, id: &str) -> String {
    match v["unit"].as_str() {
        Some("ms") => number(&v["value"], id),
        Some("s") => format!("{:?}", v["value"].as_f64().expect("seconds") * 1000.0),
        _ => panic!("{id}: a duration needs a unit of ms or s"),
    }
}

/// A number as a Rust `f64` literal.
fn number(v: &Value, id: &str) -> String {
    format!(
        "{:?}",
        v.as_f64().unwrap_or_else(|| panic!("{id}: not a number"))
    )
}

/// `card-edge` becomes `CardEdge`.
fn variant(role: &str) -> String {
    role.split('-')
        .map(|w| {
            let mut c = w.chars();
            c.next()
                .map(|f| f.to_ascii_uppercase().to_string() + c.as_str())
                .unwrap_or_default()
        })
        .collect()
}

/// `#2f6aa8` as the Rust expression of its colour.
fn rgb(hex: &str) -> String {
    let h = hex.trim_start_matches('#');
    assert!(h.len() == 6, "{hex}: a colour's hex has six digits");
    format!("Rgb([0x{}, 0x{}, 0x{}])", &h[0..2], &h[2..4], &h[4..6])
}

/// `card-edge` becomes `card_edge`.
fn field(role: &str) -> String {
    role.replace('-', "_")
}

/// `card.horizontal-height` becomes `CARD_HORIZONTAL_HEIGHT`.
fn constant(id: &str) -> String {
    id.replace(['.', '-'], "_").to_uppercase()
}
